### ISSUE TITLE
Missing step in README for Installation

### ISSUE THREAD

**Issue by Spimy** [Dusk-Labs/dim#192]
When running `cargo run`, it will stop and ask me to build the UI using `yarn build` (or I suppose any other package manager): 
![image](https://user-images.githubusercontent.com/34989646/132253772-a8edc1df-a8b9-49f0-a3ca-f028bd9126fa.png)

This step seems to be missing in the `README`. Very minor issue so I'm not sure if I should even open this as an issue.

**Comment by vgarleanu** [comment]
The README isnt very complete yet. The reason the build is failing is because `sqlite3` isnt available in your PATH. Installing sqlite3 globally should fix the issue.

Ill clarify this in the README.

**Comment by vgarleanu** [comment]
We should also state that libva and libva-drm are optional Linux dependencies.
