### ISSUE TITLE
Building UI fails during to missing "react-scripts"

### ISSUE THREAD

**Issue by Spimy** [Dusk-Labs/dim#193]
`react-scripts` seems to be missing in the dependency list so when building the UI component, it would say that it is missing. It should be listed as a dev dependency in case someone does not have it installed globally on their machine
![image](https://user-images.githubusercontent.com/34989646/132254067-53165ead-271a-4b40-9288-78483751c7d3.png)

**Comment by eraychumak** [comment]
That's weird as it is included in the dependency list, double checking, did you run `yarn` to install dependencies in the root folder? As it has to be run in `/ui`
