### ISSUE TITLE
UI stuck in infinite redirect loop between login and main page on firefox.

### ISSUE THREAD

**Issue by dessalines** [Dusk-Labs/dim#204]
dim's UI is broken, its stuck in an infinite redirect loop loading the main and login page. It only happens on firefox, not chrome.

The docker-compose logs keep showing this:

```
dim-dim-1  | Oct 19 16:02:03.046 INFO GET, mod: warp, route: /api/v1/dashboard/banner, status: 401 Unauthorized, ip: 192.168.50.20:35194, duration: 215, duration_tag: us
dim-dim-1  | Oct 19 16:02:03.167 INFO GET, mod: warp, route: /login, status: 200 OK, ip: 192.168.50.20:35182, duration: 198, duration_tag: us
dim-dim-1  | Oct 19 16:02:03.452 INFO GET, mod: warp, route: /static/css/main.f6c4e38b.chunk.css, status: 200 OK, ip: 192.168.50.20:35172, duration: 224, duration_tag: us
dim-dim-1  | Oct 19 16:02:03.455 INFO GET, mod: warp, route: /static/js/2.75e9e814.chunk.js, status: 200 OK, ip: 192.168.50.20:35182, duration: 599, duration_tag: us
dim-dim-1  | Oct 19 16:02:03.474 INFO GET, mod: warp, route: /static/js/main.d55f75db.chunk.js, status: 200 OK, ip: 192.168.50.20:35186, duration: 356, duration_tag: us
^Ccanceled
```

**Comment by vgarleanu** [comment]
This bug was probably introduced by the auto-logout logic.

**Comment by MrTimscampi** [comment]
I encountered this when first trying dim locally. Clearing the cookies and site data fixed it for me.

No errors were showing up in the console, but I'll hazard a guess that the login logic wasn't liking something in the cookies/local storage and didn't handle the failure gracefully, leading to the loop.

**Comment by eraychumak** [comment]
Assuming it's the same bug. After registering, it redirects you to login page instead of to the dashboard.

**Comment by vgarleanu** [comment]
Yeah its probably the same bug https://github.com/Dusk-Labs/dim/commit/2d1740c10a4c242956c76f05123cb40a2ef7720b.
Sigh I knew pushing this might be a bad idea T_T.

**Comment by Alcatraz077** [comment]
Oh solid thanks!
