### ISSUE TITLE
Starting binary hangs at `Summoning Dim`

### ISSUE THREAD

**Issue by s0lst1ce** [Dusk-Labs/dim#207]
Hello!
I just downloaded the binary in "release" but I can't seem to run it. The process just hangs at "INFO Summoning Dim v0.3.0-rc6..." while using 15% of my processor.

Am I missing something? I thought I followed the instruction in the README.

**Comment by mental32** [comment]
Hi @s0lst1ce that seems like normal behavior if you haven't accessed the Dim web UI yet, try opening `localhost:8000` in your browser and see if you get a response.
