### ISSUE TITLE
When Clicking "Play S1 E1" on Dim, Dim Reports "No Files Found" When Files Exist

### ISSUE THREAD

**Issue by Alcatraz077** [Dusk-Labs/dim#283]
Howdy, 

Running the dev docker image of dim (but I noticed this on non-dev as well).

When clicking on "Play S1 E1" on Dim, the file browser shows no files, but if I click into the show the files are there and will play. 
![Dim_S1E1](https://user-images.githubusercontent.com/21212254/138338017-6b36ab36-9340-41d5-945d-cabcaa06f2b9.png)
![Dim_No_Files_Found](https://user-images.githubusercontent.com/21212254/138338075-7f22a0e9-7d11-4817-8a18-c6c5a678e5cf.png)
![Dim_Files_Exist](https://user-images.githubusercontent.com/21212254/138338085-f9d2b841-8dda-495b-b69f-cdc16d7d4afd.png)

Just wanted to report this. This occurs on any show I try, and happens on Chrome as well as Firefox. Logs didn't show any sort of error or anything like that. If there's anything else needed for troubleshooting, please let me know.

**Comment by vgarleanu** [comment]
Heya, can you open the console and go to the network tab, and there should be a request for for `/media/<id>`, can you paste the response here?

**Comment by vgarleanu** [comment]
I need the json body thats contained in the response.

**Comment by Alcatraz077** [comment]
Sorry, here's that:

```json
{"added":"2021-10-21 14:23:22.961867641 UTC","backdrop_path":"images/gLACGQiS8kRP2hDnzdmIYo2uRRc.jpg","description":"Lawyer-by-day Matt Murdock uses his heightened senses from being blinded as a young boy to fight crime at night on the streets of Hell’s Kitchen as Daredevil.","duration":3175,"episode":1,"genres":["Crime","Drama","Action & Adventure"],"id":37273,"library_id":4,"media_type":"tv","name":"Marvel's Daredevil","poster_path":"images/QWbPaDxiB6LW2LjASknzYBvjMj.jpg","progress":0,"rating":8,"season":1,"year":2015}
```

Sorry it's not formatted JSON, when I tried to copy it out of the browser console it added in a bunch of html stuff.
