### ISSUE TITLE
Docker image not public

### ISSUE THREAD

**Issue by danastasio** [Dusk-Labs/dim#320]
Hello,

When I run `podman run -d -p 8000:8000/tcp -v $HOME/.config/dim:/opt/dim/config -v /media:/media ghcr.io/dusk-labs/dim`

I get the following error:

`Error: initializing source docker://ghcr.io/dusk-labs/dim:latest: reading manifest latest in ghcr.io/dusk-labs/dim: unauthorized`

I am logged into ghcr.io with podman, which leads me to believe that the image has not been made public.

**Comment by yunyuyuan** [comment]
`ghcr.io/dusk-labs/dim:dev` seems very slow to pull.

**Comment by vgarleanu** [comment]
For now we will be publishing images exclusively to ghcr to simplify our pipelines. Closing as out-of-scope.
