### ISSUE TITLE
Request for Docker Hub Image

### ISSUE THREAD

**Issue by sadstan** [Dusk-Labs/dim#323]
**Is your feature request related to a problem? Please describe.**
I prefer using Docker Hub over GHCR

**Describe the solution you'd like**
Image is also available on Docker Hub

**Describe alternatives you've considered**
Just give up and use GHCR

**Additional context**
N/A

**Comment by onedr0p** [comment]
Why? Dockerhub rate limits exist and over the past couple week fiasco Docker Inc. should not be trusted.

**Comment by vgarleanu** [comment]
As mentioned in other similar issues, for now we will be sticky to ghcr. Closing this as wont-fix.
