### ISSUE TITLE
HTTP 500 on '/api/v1/stream/2387/manifest' with 'It appears that the file is corrupted'

### ISSUE THREAD

**Issue by TheDutchMC** [Dusk-Labs/dim#327]
**Describe the bug**

When trying to play back an .mkv file containing spaces in the name (I have not verified if either of these are the culprit), Dim's `/api/v1/stream/<id>/manifest` will return a 500 error. The gui does not show this error and ends up stuck in loading. The message returned along with the error is:
```
{"error":null,"messsage":"It appears that the file is corrupted"}
```
The file however is not corrupted. Jellyfin handles playback fine

**To Reproduce**
1. Have an MKV file
2. Try to play it with Dim
3. Observe error in stdout and browser's devtools

**Expected behavior**
Either Dim tells the user it cannot play the file along with a reason why; Or Dim plays the file just fine

**Screenshots**
![image](https://user-images.githubusercontent.com/28569170/140750521-7e296d7c-121a-449a-8a3b-864061fcf688.png)

**Device and browser including versions:**
Server:
- `uname -a`: Linux dim 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- `dim -V`: `Dim 0.3.0-rc6`

Client:
- `uname -a`: `Linux tobias-desktop 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Browser: `Firefox 93.0 (64-bit)` AND `Microsoft Edge 96.0.1054.8 (Official build) beta (64-bit)`

**Additional context**
The file's exact path is `/mnt/media/tvshows/Arrow/S01/Arrow - S01E01 - Pilot Bluray-1080p.mkv`

Dim is running in an LXC with LXD v4.16, host is Ubuntu 20.04.3 LTS. A GPU is available in the container (Nvidia GTX 1070) with driver version `455.28` and CUDA `11.1`. Dim does show the following error, which might be related, at startup:
```
Nov 08 13:25:58 dim systemd[1]: Started Dim Media Server.
Nov 08 13:25:58 dim dim[253]: Nov 08 13:25:58.365 INFO
Nov 08 13:25:58 dim dim[253]: Nov 08 13:25:58.365 INFO
Nov 08 13:25:58 dim dim[253]: libva info: VA-API version 1.7.0
Nov 08 13:25:58 dim dim[253]: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Nov 08 13:25:58 dim dim[253]: Nov 08 13:25:58.366 INFO Enabling profile, profile: AacTranscodeProfile
Nov 08 13:25:58 dim dim[253]: Nov 08 13:25:58.366 INFO Enabling profile, profile: H264TranscodeProfile
Nov 08 13:25:58 dim dim[253]: Nov 08 13:25:58.366 INFO Enabling profile, profile: H264TransmuxProfile
Nov 08 13:25:58 dim dim[253]: Nov 08 13:25:58.366 INFO Enabling profile, profile: RawVideoTranscodeProfile
Nov 08 13:25:58 dim dim[253]: Nov 08 13:25:58.366 INFO Enabling profile, profile: WebvttTranscodeProfile
Nov 08 13:25:58 dim dim[253]: Nov 08 13:25:58.366 INFO Enabling profile, profile: CudaTranscodeProfile
Nov 08 13:25:58 dim dim[253]: Nov 08 13:25:58.366 WARN Disabling profile, profile: VaapiTranscodeProfile, reason: Profile not supported Device <null_device> doesnt support profile VAProfileH264ConstrainedBaseline (Supported profiles: )
``` 
It is unknown to me what this means or how to solve it.

**Comment by TheDutchMC** [comment]
That threw an error with: `utils/ffprobe: error while loading shared libraries: libtheoraenc.so.1: cannot open shared object file: No such file or directory` (I will make a PR to add this to the list of required libraries)`

After installing it the output is:
```
ffprobe version git-2021-10-19-407acc0 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-17ubuntu1~20.04)
  configuration: --pkg-config-flags=--static --prefix=/home/runner/work/ffmpeg-static/ffmpeg-static/target --bindir=/home/runner/work/ffmpeg-static/ffmpeg-static/target/bin --extra-cflags='-I /home/runner/work/ffmpeg-static/ffmpeg-static/target/include -I /usr/local/cuda/include/' --extra-ldflags='-L /home/runner/work/ffmpeg-static/ffmpeg-static/target/lib -L /usr/local/cuda/lib64/' --extra-libs=-lpthread --disable-autodetect --enable-gpl --enable-nonfree --enable-libass --enable-libfdk-aac --enable-vaapi --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libaom --enable-pthreads --enable-nvenc --enable-nvdec --enable-ffnvcodec --enable-cuda --enable-cuda-sdk
  libavutil      57.  7.100 / 57.  7.100
  libavcodec     59. 12.100 / 59. 12.100
  libavformat    59.  6.100 / 59.  6.100
  libavdevice    59.  0.101 / 59.  0.101
  libavfilter     8. 15.100 /  8. 15.100
  libswscale      6.  1.100 /  6.  1.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Missing argument for option 'V'
```
Dim is now playing too.

**Comment by vgarleanu** [comment]
Gotcha, are you using the image from dockerhub or ghcr?

**Comment by TheDutchMC** [comment]
Neither. Running in an LXC using the prebuild binary.

**Comment by vgarleanu** [comment]
> Neither. Running in an LXC using the prebuild binary.

Gotcha, I will close this issue as solved then.
