### ISSUE TITLE
Connection to the server lost

### ISSUE THREAD

**Issue by danastasio** [Dusk-Labs/dim#360]
**Describe the bug**
I am getting hundreds of these messages while using the Dim website. They appear in pairs every few seconds. They are:

"Connection to the server lost, some actions might not work"

immediately followed by:

"Connection to the server has been restored"

**To Reproduce**
1. Log into the website
2. Wait

**Expected behavior**
No error messages

**Screenshots**
![image](https://user-images.githubusercontent.com/23290366/148074674-00487670-16c0-4524-a154-57f2eb14a8d8.png)

**Device and browser including versions:**
Desktop on firefox stable v95.02 (flatpak) - Running on Fedora Silverblue

**Additional context**
Running in podman using the following command:
```podman run --privileged -dt -p 8005:8000/tcp -v $HOME/dim-config:/opt/dim/config -v /media:/media:ro --name dim ghcr.io/dusk-labs/dim:dev```

**Comment by vgarleanu** [comment]
Can the bug be reproduced if running with docker?

**Comment by danastasio** [comment]
Podman implements the docker API, so I'm fairly certain that I will have the same bug with docker that I do with podman.

It will take some time for me to install docker as I do not have it on my system, but I will try and let you know what I find.

**Comment by danastasio** [comment]
![yes](https://user-images.githubusercontent.com/23290366/148403709-a7465c1d-a22d-401b-b41e-917eff8bed8f.png)

This is running on docker, server is Fedora IoT 35. I am happy to provide logs from either instance if you point me in the direction. docker logs / podman logs only seem to show information about matching, they don't have any information about losing connection to the server.

Possibly relevant, I am using this behind a Caddy 2 reverse proxy? Issue occurs if I turn off SELinux as well.

**Comment by vgarleanu** [comment]
This issue might indeed be caused by the proxy, perhaps it's interrupting the websocket connection abruptly and the webui is retrying to connect each time.

Is there any way you can try to disable the proxy?

**Comment by danastasio** [comment]
ah ha. That makes sense. I have the server running sans proxy, I'll let you know how it goes.

**Comment by danastasio** [comment]
Yes, I think it is indeed the reverse proxy. Accessing the instance directly produces no errors, but accessing it through the reverse proxy has many errors. I'll take this issue up with them. Thanks for the help!
