### ISSUE TITLE
Cannot re-match shows that have been incorrectly identified.

### ISSUE THREAD

**Issue by danastasio** [Dusk-Labs/dim#361]
**Is your feature request related to a problem? Please describe.**
The show matching is... not good, and there is no way to re-match shows that have been incorrectly identified.

**Describe the solution you'd like**
It would be great if there was a way to correct or re-match shows that have been matched.

**Describe alternatives you've considered**
n/a

**Additional context**
I don't own any of the below shows, and none of my files suggest they should be matched to these. One of the shows is offensive and repulsive (14 year old mother) and I cannot do anything about it. Also, see the bug I mention in #360 

![image](https://user-images.githubusercontent.com/23290366/148077785-e3ec1c5d-9688-4b42-b6ab-7632eadd07a9.png)

**Comment by vgarleanu** [comment]
You might be using a old version of the server. Give the dev image a try.
