### ISSUE TITLE
Relicense to AGPLv3

### ISSUE THREAD

**Issue by vgarleanu** [Dusk-Labs/dim#362]
AGPLv3 is a more appropriate license for this project and will also let us use some crates and dependencies that are not compatible with our current GPLv2 license.

**Comment by joehillen** [comment]
> let us use some crates and dependencies that are not compatible with our current GPLv2 license.

Do you have any specific examples? Permissive licenses (e.g., MIT, BSD, Apache) can be converted to GPL, but not vice versa.

Licensing only applies to "derivative works", not libraries.

GPLv2 is a more permissive license than GPLv3, and AGPLv3 is the same as GPLv3 with the added server clause (see [here](https://opensource.stackexchange.com/questions/5041/of-the-differences-between-the-gplv3-and-the-agplv3-texts-what-to-make-of-them)), so anything compatible with GPLv2 is definitely compatible GPLv3, but you can't create a new derivate GPLv2 work from (A)GPLv3 licensed software.
