### ISSUE TITLE
Plex and Emby compatible API wrappers

### ISSUE THREAD

**Issue by DesignsWithDavid** [Dusk-Labs/dim#399]
# Problem
Currently the DIM team does not have the means of creating all of the plugins and clients that are available for competitors, namely, Apple TV apps, Android TV apps, Roku TV app, mobile apps, PC app, web clients, etc.  

# Solution
Once API and plugin system have been roughly solidified, create wrappers compatible with Plex and Emby APIs and extension frameworks so that existing tools are compatible with Dim.  This will likely ease the transition for newcomers.

# Notes
- This is by no means a small feat and it is very possible that it will be too substantial of a task to take on.  
- The philosophy is similar to that of Wayland as it intends to take over X-Server; create a bridge between the two so users have a seemless transition between their current tooling and Wayland.  If DIM could make is seemless, it is more likely users of the current tools (Plex, Emby, Jellyfin, etc) will transition.
- Additionally, this bridge would mean that any new extensions/plugins/clients developed for others would immediately become available to DIM users.

# Alternatives
- Create a DIM specific client for all devices
- Mimic the most common plugins/extensions used on competing platforms

**Comment by vgarleanu** [comment]
The APIs are also way too different in how data is mapped, making compatible wrappers would be too big of an undertaking for little benefit and just more headaches in the long run.

I'd rather focus all resources towards building native 1st party clients (starting with mobile). 

p.s. that last open issue looks pretty bad. We definitely can't be compatible with any of the behaviors described there.
