### ISSUE TITLE
Libraries with duplicate paths don't get indexed

### ISSUE THREAD

**Issue by mental32** [Dusk-Labs/dim#41]
* Create one library with a file path and set its media type to movies (name this "xxx")
* Wait for indexing to complete
* Create a second lib with the same file path as "xxx" but the media type is set to "Tv Shows"

Expected behavior: Instantly indexed due to already being indexed before so the results should be cached.

Actual behavior: Indexing never starts.

**Comment by vgarleanu** [comment]
Its been decided that this is actually expected behavior and thus will not be fixed.
