### ISSUE TITLE
What is the supported movies type

### ISSUE THREAD

**Issue by cchalifo999** [Dusk-Labs/dim#410]
What is the supported movies type

**Comment by vgarleanu** [comment]
> What is the supported movies type

If you mean filetypes,  the supported filetypes are mkv, mp4 and avi

**Comment by cchalifo999** [comment]
> > What is the supported movies type
> 
> If you mean filetypes, the supported filetypes are mkv, mp4 and avi
ty 
i trued add a mkv mp4 im my med folder and it is not showing

**Comment by cchalifo999** [comment]
an

> > What is the supported movies type
> 
> If you mean filetypes, the supported filetypes are mkv, mp4 and avi

and here are the screen shot
![Screenshot-dim_2022-02-21_11-55-09](https://user-images.githubusercontent.com/2941510/154998561-c7f5d404-0487-45f2-b02a-a3bce8c6da65.png)
![Screenshot_Media_2022-02-21_11-55-57](https://user-images.githubusercontent.com/2941510/154998563-cfc2c81c-3162-419a-946c-4a4b2cfd65b4.png)

**Comment by vgarleanu** [comment]
> an
> 
> > > What is the supported movies type
> > 
> > If you mean filetypes, the supported filetypes are mkv, mp4 and avi
> 
> and here are the screen shot
> ![Screenshot-dim_2022-02-21_11-55-09](https://user-images.githubusercontent.com/2941510/154998561-c7f5d404-0487-45f2-b02a-a3bce8c6da65.png)
> ![Screenshot_Media_2022-02-21_11-55-57](https://user-images.githubusercontent.com/2941510/154998563-cfc2c81c-3162-419a-946c-4a4b2cfd65b4.png)
> 
> 
> 

You should go back a directory and select the entire media folder by hovering over it and ticking the checkbox.

**Comment by cchalifo999** [comment]
> > an
> > > > What is the supported movies type
> > > 
> > > 
> > > If you mean filetypes, the supported filetypes are mkv, mp4 and avi
> > 
> > 
> > and here are the screen shot
> > ![Screenshot-dim_2022-02-21_11-55-09](https://user-images.githubusercontent.com/2941510/154998561-c7f5d404-0487-45f2-b02a-a3bce8c6da65.png)
> > ![Screenshot_Media_2022-02-21_11-55-57](https://user-images.githubusercontent.com/2941510/154998563-cfc2c81c-3162-419a-946c-4a4b2cfd65b4.png)
> 
> You should go back a directory and select the entire media folder by hovering over it and ticking the checkbox.

Ty  that help
and i love the program keep up the good work
