### ISSUE TITLE
high cpu usage v0.3.0-rc6

### ISSUE THREAD

**Issue by jasond2020** [Dusk-Labs/dim#421]
**Describe the bug**
High CPU usage without any interaction

**To Reproduce**
Install an plain debian
get release as zip and untar
start dim
go to webpage and create admin account
do nothing else, just check the system load

**Expected behavior**
no (noticeable) cpu usage/system load should happen if nothing is done (especially if no library is active)

**Device and browser including versions:**
server debian 11.2
client debian 11.2 with chromium 99.0.484451...

**Comment by vgarleanu** [comment]
The cpu usage has been fixed, it just hasn't made it into a new release, but is available in the dev docker builds.
