### ISSUE TITLE
Full conversion to Typescript

### ISSUE THREAD

**Issue by joehillen** [Dusk-Labs/dim#427]
Hi, I'm very interested in this project, and I'm looking for ways to contribute. One way I could help is by converting to Typescript. Although there are some `.ts` files, it looks like all the React files are `.jsx` and `.d.ts`. This is a bit unusual for a new project. Is there a reason for this? Would you like me to help convert them?

**Comment by vgarleanu** [comment]
Closing as duplicate of #212 . However please feel free to contribute by joining our discord server where we coordinate development :)
