### ISSUE TITLE
Public Facing side

### ISSUE THREAD

**Issue by trashcluster** [Dusk-Labs/dim#430]
Would be nice to have a public facing interface or more granular rights for read only users for example

**Comment by trashcluster** [comment]
> I am not sure what kind of use this has besides essentially making a pirate streaming site. We can definitely accommodate more granular permissions for users tho.

I was mostly thinking at the ease of sharing but in the end it essentially become a pirate website yes :)
A more restrictive permission set would be better suited then. As of today any invited user has editing access and can remove libraries.
A "viewer" access would be perfect

**Comment by niamu** [comment]
I think this has effectively been addressed by https://github.com/Dusk-Labs/dim/pull/581

**Comment by jacobkossman** [comment]
I think granular user access controls via tags, filters, rating etc would be exceptional. So having an "admin" / "owner" role and then allowing access per library, etc

**Comment by niamu** [comment]
@jacobkossman I think that's better covered by https://github.com/Dusk-Labs/dim/issues/210
