### ISSUE TITLE
Request coalescing

### ISSUE THREAD

**Issue by mental32** [Dusk-Labs/dim#434]
Amos' blog post explaining request coalescing: https://fasterthanli.me/articles/request-coalescing-in-async-rust

## quick walk through

As the scanners run for some library (lets assume it's a tv show or mixed lib with shows inside.)
```rust
    let mut futures = Vec::new();

    for file in files {
        futures.push(async move {
            if let Ok(mfile) = extractor
                .mount_file(file.clone(), library_id, media_type, do_update)
                .await
            {
                match media_type {
                    MediaType::Movie => {
                        let _ = matcher.match_movie(mfile).await;
                    }
                    MediaType::Tv => {
                        let _ = matcher.match_tv(mfile).await;
                    }
                    _ => unreachable!(),
                }
            }
        })
    }

    futures::future::join_all(futures).await;
```
Calls to either `match_movie` or `match_tv` are made, which will all eventually enter `search_by_name`
```rust
    #[async_recursion]
    pub async fn search_by_name(
        &mut self,
        title: String,
        year: Option<i32>,
        max_tries: Option<usize>,
    ) -> Result<Vec<Media>, TmdbError> {
```
Which will use this caching logic
```rust
        type CacheKey = (String, Option<i32>, MediaType);
        type CacheStore = Arc<RwLock<HashMap<CacheKey, Vec<Media>>>>;

        lazy_static::lazy_static! {
            static ref __CACHE: CacheStore = Arc::new(RwLock::new(HashMap::new()));
        }

        {
            let lock = (*__CACHE).read().await;
            let key = (title.clone(), year, self.media_type);

            if let Some(x) = lock.get(&key) {
                return Ok(x.to_vec());
            }
        }

        // -- SNIP

        let url = format!("{}/search/{}", self.base, self.media_type);

        let req = self
            .client
            .get(url)
            .query(&args)
            .send()
            .await
            .map_err(|_| TmdbError::ReqwestError)?;

        if matches!(req.status(), StatusCode::TOO_MANY_REQUESTS) {
            tokio::time::sleep(Duration::from_millis(1000)).await;
            return self.search_by_name(title, year, Some(max_tries - 1)).await;
        }

        // -- SNIP

        {
            let mut lock = (*__CACHE).write().await;
            let key = (title.clone(), year, self.media_type);
            lock.insert(key, result.clone());
        }
```
So imagine we have 40 files in the tree of a library and the extractor has passed 30 of them, maybe 10 didn't pass because of a bad filename or ffprobe result. that's still 30 requests that will be made and if they're the same tv show multiple requests can be made to tmdb all for the same tv show object.

Here the redundant requests will be made until whichever one can make it first to inserting itself into the cache but depending on how quickly this rest of the code runs this has the potential worst case of letting through all or most of the same requests since the checking critical section does not account for if there is already a request running ergo request coalescing would be the solution for this here.

## potential benefits

* increase scanner performance (maybe? I think the majority of time spent is in the db updating, so batching would also be needed there.)
* better usage of networking bandwidth. not exactly a wow factor but its always good to be greener!
* an excuse to rewrite the scanner/tmdb/caching logic to make it more flexible and optimized also an excuse to write tests for the new code and benchmark it to look good in the changelog when we get a 200x perf increase :sunglasses: 
* bragging rights.

**Comment by vgarleanu** [comment]
Closing as this has been implemented by PR https://github.com/Dusk-Labs/dim/pull/448
