### ISSUE TITLE
when yarn install take a ./autogen.sh: not found error

### ISSUE THREAD

**Issue by zjhzxy** [Dusk-Labs/dim#444]
rm -rf build/lib/fribidi
mkdir -p build/lib
cp -r lib/fribidi build/lib/fribidi
true
cd build/lib/fribidi && NOCONFIGURE=1 ./autogen.sh
/bin/sh: 1: ./autogen.sh: not found
make: *** [Makefile:19: build/lib/fribidi/configure] Error 127
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

When I run this command：yarn --cwd ui/ && yarn --cwd ui/ build  An error was reported。 How to solve this problem？

**Comment by vgarleanu** [comment]
We need a bit more info. What OS are you running on? I'm not sure why you're manually building libfribidi.

**Comment by vgarleanu** [comment]
This could be related to #436

**Comment by krevoit** [comment]
same issue on Ubuntu.

**Comment by vgarleanu** [comment]
Can you pull latest master, and try building again#?
