### ISSUE TITLE
"1 Unmatched files found"

### ISSUE THREAD

**Issue by DUOLabs333** [Dusk-Labs/dim#451]
**Describe the bug**
I have a mkv file in a folder. However, dim just says "1 Unmatched files found", and I can't select it.

**To Reproduce**
1. Download an mkv
2. Add it to your folder
3. See nothing shows up

**Expected behavior**
My files show up

**Screenshots**
![image](https://user-images.githubusercontent.com/49244768/174388881-453157a5-b469-49b2-90b1-f3f2caa14112.png)

**Device and browser including versions:**
Desktop, Firefox 89

**Additional context**

**Comment by DUOLabs333** [comment]
I had to change the type to "Show" instead of movie. Maybe make it so it should not matter?

**Comment by vgarleanu** [comment]
Seems like fonts arent loading properly, might be styling issues too. Can you open the network console and screenshot all requests. Some might be failing.

If the MKV file is randomly named itd need to be manually matched to a tv show or a movie before it shows up;

**Comment by DUOLabs333** [comment]
Is it possible to allow for arbitrary files?
