### ISSUE TITLE
ffmpeg using 100% CPU despite "direct play" quality setting

### ISSUE THREAD

**Issue by xbjfk** [Dusk-Labs/dim#458]
**Describe the bug**
When selecting Direct Play quality in the UI the video is stuttery and ffmpeg uses 100% cpu

**To Reproduce**
Attempt to play a video on a low quality device with direct play enabled

**Expected behavior**
ffmpeg uses little CPU or ffmpeg is not ran at all

**Screenshots**
N/A

**Device and browser including versions:**
desktop firefox flatpak 102.0.1

**Additional context**
N/A

**Comment by xbjfk** [comment]
Actually, this laggy video seems to be the fault of the firefox flatpak, as playing on another browser works fine. ffmpeg being on 100% cpu seems to be the result of audio transcoding, which seems unavoidable on this low spec server.
Sorry for the false issue and thank you for your work

**Comment by vgarleanu** [comment]
No worries. I hear flatpak is generally pretty bad performance wise. That said I'd like to know what format the audio is, perhaps we can avoid transcoding it. Do you mind telling me what the specs of the server are and what format the audio is?

**Comment by xbjfk** [comment]
The server is an arm tv box with an amlogic s905x4, but the audio format was ac1, so transcoding appears unavoidable as no browser seems to support it.
