### ISSUE TITLE
progress_idx not created in sqlite

### ISSUE THREAD

**Issue by julianandrews** [Dusk-Labs/dim#475]
**Describe the bug**

The unique index on `(user_id, media_id)` isn't being created (at least using sqlite 3.34.1, the default in Debian stable).

Without this index, the `INSERT OR REPLACE INTO` queries run on the progress API create new entries each time, which leads to massive over-reporting of time spent watching (which is what led me to this bug in the first place), and probably other bugs.

**To Reproduce**

Clone the repo and build dim.

```
$ cargo --version
cargo 1.63.0 (fd9c4297c 2022-07-01)
$ cargo build
...
$ sqlite3 dim_dev.db 
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> .schema progress
CREATE TABLE progress (
    id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    delta INTEGER NOT NULL,
    media_id INTEGER NOT NULL,
    populated INTEGER NOT NULL,

    PRIMARY KEY (id),
    FOREIGN KEY(media_id) REFERENCES _tblmedia (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
```

I see the same schema on a non dev DB and a `--release` build.

**Expected behavior**

There should be a unique index in the schema:

```
CREATE UNIQUE INDEX progress_idx ON progress(user_id, media_id);
```

**Additional context**

While I was poking around, I noticed that there's a `media_excl_ep_idx` index in the migrations that looks as if it also wasn't created. All the other indices in the main migration look as if they were created correctly in my database.

**Comment by julianandrews** [comment]
I'll note that manually adding the index to a new database fixes the over-reporting of time spent watching for me.

I was going to try to fix this bug myself, but I'm not super familiar with `sqlx` migrations, so once I figured out that the migration had the correct index in there and for some reason it just isn't running, I decided I probably wouldn't have time to debug this properly.

**Comment by vgarleanu** [comment]
Thanks for reporting this. Did you notice this issue in the rc6 image or the dev image?

**Comment by julianandrews** [comment]
> Thanks for reporting this. Did you notice this issue in the rc6 image or the dev image?

I built off of the head of the master branch. I originally noticed it running the release build there. Though using the debug build, `dim_dev.db` has the same schema for `progress`.
