### ISSUE TITLE
Error when upload profile picture

### ISSUE THREAD

**Issue by rodrimarchese** [Dusk-Labs/dim#502]
**Describe the bug**
Can't upload a profile picture. Receiving Database error. (500 in network)

**To Reproduce**
1. Go to System preferences
2. Click on Profile
3. Select a new picture as avatar
4. click "save as new avatar" button
5. (No UI reference to error is shown). Nothing happens

**Expected behavior**
Expect to save new image, or at least show that an error ocurred.

**Screenshots**
![image](https://user-images.githubusercontent.com/32769860/203873977-da2acc3d-de9d-4ee5-9f79-91282663aea8.png)
![image](https://user-images.githubusercontent.com/32769860/203874086-41cc9156-ce21-4a99-8afa-f305a830eb17.png)

**Device and browser including versions:**
Chrome Version 107.0.5304.110 (Official Build) (arm64)

**Comment by Droppisalt** [comment]
Thumbing this up, as I'm having the same problem (error only shown in browser console).
Happened in FF, Chrome and Edge.

**Comment by vikassahu29** [comment]
Is it okay if I start working on this issue?

**Comment by Droppisalt** [comment]
Updating to the latest version seems to have fixed this! Thanks @vgarleanu
