### ISSUE TITLE
Content just goes missing

### ISSUE THREAD

**Issue by SleeperSmith** [Dusk-Labs/dim#513]
**Describe the bug**
EDIT: Sorry correction. It shows up as "Multiple file found" on the Season 1 Episode 1, but there's no way to fix it?

For Monogatari, none of season 2+ shows up
- They are in separate folders
- They do not show as "unmatched"
- There's only 1 season in Monogatari

**To Reproduce**
Not sure.

**Expected behavior**
I expected those seasons/episodes to show up as unmatched. Could it be that they are matched to season 1 and then gets flattened/hidden?

**Device and browser including versions:**
This is a backend issue (I think).

**Additional context**
IMO, we need ability to trach where/how the files are matched. At the moment, once a piece of content has been matched, there's no way to interact / fix it.

**Comment by SleeperSmith** [comment]
After some consideration, I'll close this issue as it's probably a known limitation. I'm sure you guys have some plans for this at some point.

**Comment by vgarleanu** [comment]
I'm pretty sure this is the case. Monogatari is iffy, it's highly likely the episodes matched as the wrong season.

This will be investigated once everyone is back from their holidays.

**Comment by SleeperSmith** [comment]
@vgarleanu i did some digging myself. Essentially i think it boils down to the season being on the folder name, not on the filename. I see you guys are using Anitomy package
https://github.com/Dusk-Labs/dim/blob/master/dim/src/external/filename.rs#L30

and feeding in the name of the file only
https://github.com/Dusk-Labs/dim/blob/bb6c1f778dd77fb5c96f1179146d601e8cf083b5/dim/src/scanner/mod.rs#L100

I'm relatively certain any content I have that conforms to the parsing rules of Anitomy on the filename (e.g. having S01E01 in the filename, not folder) works fine.

Now, I have no idea how this fits in with you guys grand scheme of things. While extending the parsing to the parent / full file path may solve this particular problem, it might be a better idea to device an override of some sort.

Perhaps a way to drop a json/yaml in the folder / as a side car to a file? Then have another metadata provider that takes precedence over all others (per property, as I'd only want to override season in this case). It sort of sets up some infrastructure for metadata pinning on the disk itself?

Neways, just food for thoughts. The app looks good :) thanks for all the hard work.
