### ISSUE TITLE
Version Number Information 

### ISSUE THREAD

**Issue by Droppisalt** [Dusk-Labs/dim#533]
**Is your feature request related to a problem? Please describe.**
Not really a problem/frustration, just thought it would be a simple QoL update.

**Describe the solution you'd like**
Ability to add the version number (maybe in the bottom left? See image). Could either be an always-on thing, or an opt-in setting.
![image](https://user-images.githubusercontent.com/67336980/229653566-ae7675d1-3cd0-4be6-b61a-03528a2b66b2.png)

**Describe alternatives you've considered**
Or just somewhere in the settings of Dim.

**Comment by lathama** [comment]
That logo is at https://github.com/Dusk-Labs/dim/blob/3d81a1441ef865e22b849dcc1ca523e8dd4c7282/ui/src/Components/Sidebar/Toggle.tsx#L85 so you need to get the version from Cargo.toml as CARGO_PKG_VERSION or populate in the build.

Do you think the version should be visible or on-hover(alt)?

**Comment by DblK** [comment]
Maybe add the commit hash also, I can user use the `dev` branch so it could be either to fix issue since we will know the commit.
