### ISSUE TITLE
WebSocket communication is broken

### ISSUE THREAD

**Issue by niamu** [Dusk-Labs/dim#590]
**Describe the bug**
Since https://github.com/Dusk-Labs/dim/pull/537 WebSocket communication is not functioning. The frontend sends the initial authentication token to the backend but no messages from the server to the client work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch Dim server and visit any Dim web page with the Web Inspector open
2. Confirm adding/deleting a Library does not result in any WebSocket messages

**Expected behaviour**
It is expected that adding and removing a library results in WebSocket messages that produce live UI updates to show adding or removing media items.

**Additional context**
The following patch helps illustrate the problem and shows that `CtrlEvent::Track` events do not fire to track the remote address of the client connected. This results in any `CtrlEvent::SendAll` and `CtrlEvent::SendTo` events being processed to not have any remote address to send data to.

```patch
diff --git a/dim-web/src/routes/websocket.rs b/dim-web/src/routes/websocket.rs
index 4143ad07..7cc2bcbc 100644
--- a/dim-web/src/routes/websocket.rs
+++ b/dim-web/src/routes/websocket.rs
@@ -49,8 +49,8 @@ where
 
 async fn ctrl_event_processor<A, T>(mut rx: mpsc::Receiver<CtrlEvent<A, T>>)
 where
-    A: Hash + Eq + Clone,
-    T: ToOwned<Owned = String> + Send,
+    A: Hash + Eq + Clone + std::fmt::Debug,
+    T: ToOwned<Owned = String> + Send + std::fmt::Debug,
 {
     let mut peers = HashMap::new();
     let mut discard = vec![];
@@ -66,14 +66,17 @@ where
 
         match ev {
             CtrlEvent::Track { addr, sink, auth } => {
+                println!("CtrlEvent::Track: {:?}", addr);
                 peers.insert(addr, (sink, auth));
             }
 
             CtrlEvent::Forget { ref addr } => {
+                println!("CtrlEvent::Forget");
                 peers.remove(addr);
             }
 
             CtrlEvent::SendAll(body) => {
+                println!("CtrlEvent::SendAll {:?}", body);
                 for (addr, (sink, _)) in peers.iter_mut() {
                     let result = sink.send(WsMessage::Text(body.to_owned())).await;
 
@@ -85,6 +88,7 @@ where
             }
 
             CtrlEvent::SendTo { addr, message } => {
+                println!("CtrlEvent::SendTo {:?} {:?}", addr, message);
                 if let Some((sink, _)) = peers.get_mut(&addr) {
                     let result = sink.send(WsMessage::Text(message.to_owned())).await;
 
@@ -248,8 +252,8 @@ pub fn event_repeater<S, T, A, M>(
 where
     S: Stream<Item = T> + Send + 'static,
     T: IntoCtrlEvent<A, M> + Send,
-    A: Hash + Eq + Clone + Send + Sync + 'static,
-    M: ToOwned<Owned = String> + Send + Sync + 'static,
+    A: Hash + Eq + Clone + Send + Sync + 'static + std::fmt::Debug,
+    M: ToOwned<Owned = String> + Send + Sync + 'static + std::fmt::Debug,
 {
     let (tx, rx) = mpsc::channel::<CtrlEvent<A, M>>(capacity);
```

**Comment by niamu** [comment]
I have a suspicion that this code might be what is missing: https://github.com/Dusk-Labs/dim/pull/537/files#diff-9d8398b0a6b04253ee7ed0a8a05a070c065d3c3970502b927bcd131acde0d889L202-L210

**Comment by vgarleanu** [comment]
Could it be that the client is closing the connections too early? I want to debug this but it doesnt look like a priority atm.

**Comment by niamu** [comment]
The connection is remaining open from what the browser reports
