### ISSUE TITLE
The search does not work

### ISSUE THREAD

**Issue by VlaK0r** [Dusk-Labs/dim#599]
**Describe the bug**
The search does not work

**Screenshots**
![изображение](https://github.com/Dusk-Labs/dim/assets/77666575/26edb963-242a-4d8a-add9-3fc516d656cd)

**Device and browser including versions:**
Raspberry Pi 4
Firefox 121.0 (64)
Docker
    image: ghcr.io/dusk-labs/dim:master

**Comment by vgarleanu** [comment]
The big bang theory is a TV show not a movie. But you are searching for a movie

**Comment by vgarleanu** [comment]
Mhm might be that tmdb's api changed or our api key expired. Server logs would be useful here!

**Comment by VlaK0r** [comment]
> Mhm might be that tmdb's api changed or our api key expired. Server logs would be useful here!

It looks like my PROVIDER is blocking www.themoviedb.org

**Comment by vgarleanu** [comment]
Like your DNS provider? That's crazy

**Comment by VlaK0r** [comment]
> Like your DNS provider? That's crazy

This is Russia

**Comment by vgarleanu** [comment]
> > Like your DNS provider? That's crazy
> 
> This is Russia

Ah, yes. I suggest a VPN, or maybe we can add proxy support to dim?

**Comment by VlaK0r** [comment]
> Ah, yes. I suggest a VPN, or maybe we can add proxy support to dim?

I'm trying to connect via VPN.
And I haven't figured out the proxy yet.
Thanks for the help.
